version: '3.8'

services:
  web:
    image: flask
    container_name: bt_flask
    restart: on-failure
    build:
      context: ./flask
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=postgresql://postgres:admin123@pg_container:5432/behavior_tracker
    command: >
      sh -c "flask db upgrade && python seed.py && python bt_fake_data.py && flask run"
    depends_on:
      - pg
  pg:
    container_name: pg_container
    image: postgres:14.1-alpine3.15
    restart: always
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: admin123
        POSTGRES_DB: behavior_tracker
        POSTGRES_HOST_AUTH_METHOD: trust
        PGUSER: postgres
    ports:
        - "5432:5432"
    volumes:
        - ./data:/data
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:6.4
    restart: always
    environment:
        PGADMIN_DEFAULT_EMAIL: admin@example.com
        PGADMIN_DEFAULT_PASSWORD: admin123
        PGADMIN_LISTEN_PORT: 5433
        PGADMIN_CONFIG_SERVER_MODE: "False"
        PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
        - "5433:5433"
    depends_on:
        - pg