version: '3.8'

services:
  web:
    image: flask
    container_name: bt_flask
    build:
      context: .
      dockerfile: ./flask/Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - pg
  pg:
    container_name: pg_container
    image: postgres:14.1-alpine3.15
    restart: always
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: admin123
        POSTGRES_DB: nc_tutorials_db
        POSTGRES_HOST_AUTH_METHOD: trust
    ports:
        - "5432:5432"
    volumes:
        - ./data:/data
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:6.4
    restart: always
    environment:
        PGADMIN_DEFAULT_EMAIL: admin@example.com
        PGADMIN_DEFAULT_PASSWORD: admin123
        PGADMIN_LISTEN_PORT: 5433
        PGADMIN_CONFIG_SERVER_MODE: "False"
        PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
        - "5433:5433"
    depends_on:
        - pg