"""Added ON DELETE CASCASE to all bridge tables for behaviors foreign key

Revision ID: c1abd6b9b6f4
Revises: 059b358eeb45
Create Date: 2023-07-19 19:05:06.132021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1abd6b9b6f4'
down_revision = '059b358eeb45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('behaviors_activities_behavior_id_fkey', 'behaviors_activities', type_='foreignkey')
    op.create_foreign_key('behaviors_activities_behavior_id_fkey', 'behaviors_activities', 'behaviors', ['behavior_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('behaviors_antecedents_behavior_id_fkey', 'behaviors_antecedents', type_='foreignkey')
    op.create_foreign_key('behaviors_antecedents_behavior_id_fkey', 'behaviors_antecedents', 'behaviors', ['behavior_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('behaviors_behavior_desc_behavior_id_fkey', 'behaviors_behavior_desc', type_='foreignkey')
    op.create_foreign_key('behaviors_behavior_desc_behavior_id_fkey', 'behaviors_behavior_desc', 'behaviors', ['behavior_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('behaviors_consequences_behavior_id_fkey', 'behaviors_consequences', type_='foreignkey')
    op.create_foreign_key('behaviors_consequences_behavior_id_fkey', 'behaviors_consequences', 'behaviors', ['behavior_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('behaviors_settings_behavior_id_fkey', 'behaviors_settings', type_='foreignkey')
    op.create_foreign_key('behaviors_settings_behavior_id_fkey', 'behaviors_settings', 'behaviors', ['behavior_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('behaviors_subjects_behavior_id_fkey', 'behaviors_subjects', type_='foreignkey')
    op.create_foreign_key('behaviors_subjects_behavior_id_fkey', 'behaviors_subjects', 'behaviors', ['behavior_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('observing_staff_behavior_id_fkey', 'observing_staff', type_='foreignkey')
    op.create_foreign_key('observing_staff_behavior_id_fkey', 'observing_staff', 'behaviors', ['behavior_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('observing_staff_behavior_id_fkey', 'observing_staff', type_='foreignkey')
    op.create_foreign_key('observing_staff_behavior_id_fkey', 'observing_staff', 'behaviors', ['behavior_id'], ['id'])
    op.drop_constraint('behaviors_subjects_behavior_id_fkey', 'behaviors_subjects', type_='foreignkey')
    op.create_foreign_key('behaviors_subjects_behavior_id_fkey', 'behaviors_subjects', 'behaviors', ['behavior_id'], ['id'])
    op.drop_constraint('behaviors_settings_behavior_id_fkey', 'behaviors_settings', type_='foreignkey')
    op.create_foreign_key('behaviors_settings_behavior_id_fkey', 'behaviors_settings', 'behaviors', ['behavior_id'], ['id'])
    op.drop_constraint('behaviors_consequences_behavior_id_fkey', 'behaviors_consequences', type_='foreignkey')
    op.create_foreign_key('behaviors_consequences_behavior_id_fkey', 'behaviors_consequences', 'behaviors', ['behavior_id'], ['id'])
    op.drop_constraint('behaviors_behavior_desc_behavior_id_fkey', 'behaviors_behavior_desc', type_='foreignkey')
    op.create_foreign_key('behaviors_behavior_desc_behavior_id_fkey', 'behaviors_behavior_desc', 'behaviors', ['behavior_id'], ['id'])
    op.drop_constraint('behaviors_antecedents_behavior_id_fkey', 'behaviors_antecedents', type_='foreignkey')
    op.create_foreign_key('behaviors_antecedents_behavior_id_fkey', 'behaviors_antecedents', 'behaviors', ['behavior_id'], ['id'])
    op.drop_constraint('behaviors_activities_behavior_id_fkey', 'behaviors_activities', type_='foreignkey')
    op.create_foreign_key('behaviors_activities_behavior_id_fkey', 'behaviors_activities', 'behaviors', ['behavior_id'], ['id'])
    # ### end Alembic commands ###
