"""create observing_staff table

Revision ID: ad75e16d3840
Revises: e7491f5d4356
Create Date: 2023-07-07 13:56:33.929799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad75e16d3840'
down_revision = 'e7491f5d4356'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('observing_staff',
    sa.Column('behavior_id', sa.Integer(), nullable=False),
    sa.Column('staff_present', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['behavior_id'], ['behaviors.id'], ),
    sa.ForeignKeyConstraint(['staff_present'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('behavior_id', 'staff_present')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('observing_staff')
    # ### end Alembic commands ###
