"""create behavior_antecedent, behavior_behavior_desc, behavior_consequence tables

Revision ID: 9f211bf6d33b
Revises: ad75e16d3840
Create Date: 2023-07-07 13:58:31.979034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f211bf6d33b'
down_revision = 'ad75e16d3840'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('behaviors_antecedents',
    sa.Column('behavior_id', sa.Integer(), nullable=False),
    sa.Column('antecedent_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['antecedent_id'], ['antecedents.id'], ),
    sa.ForeignKeyConstraint(['behavior_id'], ['behaviors.id'], ),
    sa.PrimaryKeyConstraint('behavior_id', 'antecedent_id')
    )
    op.create_table('behaviors_behavior_desc',
    sa.Column('behavior_id', sa.Integer(), nullable=False),
    sa.Column('behavior_desc_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['behavior_desc_id'], ['behavior_desc.id'], ),
    sa.ForeignKeyConstraint(['behavior_id'], ['behaviors.id'], ),
    sa.PrimaryKeyConstraint('behavior_id', 'behavior_desc_id')
    )
    op.create_table('behaviors_consequences',
    sa.Column('behavior_id', sa.Integer(), nullable=False),
    sa.Column('consequence_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['behavior_id'], ['behaviors.id'], ),
    sa.ForeignKeyConstraint(['consequence_id'], ['consequences.id'], ),
    sa.PrimaryKeyConstraint('behavior_id', 'consequence_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('behaviors_consequences')
    op.drop_table('behaviors_behavior_desc')
    op.drop_table('behaviors_antecedents')
    # ### end Alembic commands ###
