"""create student, staff, behavior tables

Revision ID: f2698a77d25c
Revises: 
Create Date: 2023-07-07 13:48:51.331335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2698a77d25c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.Text(), nullable=False),
    sa.Column('last_name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.Text(), nullable=False),
    sa.Column('last_name', sa.Text(), nullable=False),
    sa.Column('grade', sa.String(length=2), nullable=False),
    sa.Column('case_manager', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['case_manager'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_table('behaviors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student', sa.Integer(), nullable=False),
    sa.Column('antecedent_other', sa.Text(), nullable=True),
    sa.Column('behavior_other', sa.Text(), nullable=True),
    sa.Column('consequence_other', sa.Text(), nullable=True),
    sa.Column('date_of_behavior', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['student'], ['students.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('behaviors')
    op.drop_table('students')
    op.drop_table('staff')
    # ### end Alembic commands ###
